# Porta di Quarkus
quarkus.http.port=8081

# Configurazione Database H2 con fix per la persistenza in memoria
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:anagrafe;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

# Filtro CORS (già gestito dalla classe Java, ma teniamo le property coerenti)
# quarkus.http.cors=true
# quarkus.http.cors.origins=*
# quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS