# Porta del microservizio
quarkus.http.port=8081

# Configurazione Database H2 (DEVE ESSERE ATTIVA)
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:anagrafe;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create

# Configurazione Canale Kafka in USCITA (Producer)
mp.messaging.outgoing.cittadino-creato.connector=smallrye-kafka
mp.messaging.outgoing.cittadino-creato.topic=cittadini-events
mp.messaging.outgoing.cittadino-creato.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer