quarkus.http.port=8082

# Connessione al broker Kafka (Solo in INGRESSO)
mp.messaging.incoming.cittadini-in.connector=smallrye-kafka
mp.messaging.incoming.cittadini-in.topic=cittadini-events

# Diciamo a Kafka di usare la nostra classe custom per leggere il JSON
mp.messaging.incoming.cittadini-in.value.deserializer=it.esempio.model.CittadinoDeserializer