quarkus.http.port=8083
quarkus.application.name=registro-storico-service

# Configurazione Canale Kafka in INGRESSO
mp.messaging.incoming.storico-in.connector=smallrye-kafka
# ATTENZIONE: Assicurati che il nome del topic coincida esattamente con quello del Producer! (cittadini-events)
mp.messaging.incoming.storico-in.topic=cittadini-events

# FORZIAMO UN GRUPPO DIVERSO PER EVITARE IL LOAD BALANCING
mp.messaging.incoming.storico-in.group.id=registro-storico-group

# Deserializzatore Custom
mp.messaging.incoming.storico-in.value.deserializer=it.esempio.model.CittadinoDeserializer